# action.yml
name: "DbChange Action"
description: "Run DbUp and re-generate database schema scripts"
inputs:
  db-connection:
    description: "The ADO.Net connection string to connect to your database"
    required: true
    default: ""
  db-environment:
    description: "The name of the environment (dev/stage/prod) we are operating in"
    required: true
    default: "dev"
  path-dbup-scripts:
    description: "The path to the scripts used to upgrade the database"
    required: true
    default: ""
  path-schema-scripts:
    description: "The path to write the current schema to"
    required: true
    default: ""
  git-schema-branch:
    description: "The branch use when commiting schema changes"
    required: false
    default: "master"
  git-email:
    description: "The email of the identity to use when commiting schema changes"
    required: false
    default: "dbchange@datasubstrate.com"
  git-name:
    description: "The name of the identity to use when commiting schema changes"
    required: false
    default: "DbChange Robot"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "docker://growingdata/db-change:v1.0.3"
  entrypoint: "/db-change/action-runner.sh"
  args:
    - ${{ inputs.db-connection }}
    - ${{ inputs.db-environment }}
    - ${{ inputs.path-dbup-scripts }}
    - ${{ inputs.path-schema-scripts }}
    - ${{ inputs.git-schema-branch }}
    - ${{ inputs.git-email }}
    - ${{ inputs.git-name }}
