name: build

on:
  push:
    branches:
      - "feature/**"

jobs:
  build:
    runs-on: [ubuntu-20.04]
    container:
      image: docker.io/growingdata/ds8-cicd:1.0.0
    steps:
      # Check out the repository
      - name: checkout-code
        uses: actions/checkout@v2

      # Build the image
      - name: build
        run: |
          echo "Building dotnet..."
          dotnet publish ./src/DbChange/DbChange.csproj -r linux-musl-x64 -c Release -o ./bin

      - name: build-image
        run: |
          echo "Building image..."
          docker build -t $IMAGE_DBCHANGE_DEV:SHORT_SHA -f ./src/docker/db-change.Dockerfile ./bin

      - name: docker-push
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          IMAGE_DBCHANGE_DEV: ${{ secrets.IMAGE_DBCHANGE_DEV }}

        run: |
          echo "Pushing dev image to dockerhub..."
          SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")
          docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD docker.io
          docker push $IMAGE_DBCHANGE_DEV:SHORT_SHA
